#!/usr/bin/env python3
"""
Generates database/06_seed_data.sql — a large, realistic sample dataset
for the Library Management System.

This script does NOT touch schema/views/functions/procedures/triggers.
It only emits plain SQL (INSERT/UPDATE statements using the existing
schema and calling the existing fn_calculate_fine() function) that
loads through the normal database/01-05 scripts unchanged.

Design notes on how historical circulation history is seeded safely:
  - trg_before_issue_insert blocks any INSERT into book_issues once a
    book's available_copies hits 0, and trg_after_issue_insert
    decrements available_copies on every insert regardless of the
    row's status. To avoid exhausting a book's stock while seeding
    hundreds of *already-returned* historical loans, each historical
    "returned" record is written the same way the real app would
    produce it: INSERT as status='issued' (decrements stock), then
    immediately UPDATE to status='returned' (trg_after_return_update
    restocks it). Net effect on available_copies is zero, exactly like
    a real issue+return cycle — no reconciliation hack needed.
  - fine_amount for returned rows is computed by the UPDATE statement
    itself via fn_calculate_fine(due_date, return_date) — the same
    function the real sp_return_book procedure uses — so the seed data
    is guaranteed consistent with the live business logic.
  - fine_paid / fine_payments are assigned afterwards with a
    deterministic MOD(issue_id, 10) bucket over rows where
    fine_amount > 0, so re-running this generator always produces the
    same paid/partial/unpaid mix.

Run:  python3 generate_seed_data.py > 06_seed_data.sql
"""
import random
from datetime import date, timedelta

random.seed(42)

OUT = []


def emit(sql):
    OUT.append(sql)


def esc(s):
    return s.replace("'", "''")


# =====================================================================
# HEADER
# =====================================================================
emit("""-- =====================================================================
-- LIBRARY MANAGEMENT SYSTEM — SAMPLE DATASET (expanded, production-scale)
-- File: 06_seed_data.sql
-- Auto-generated by database/generate_seed_data.py — do not hand-edit;
-- change the generator and regenerate instead.
--
-- Scale: 10 categories, 15 publishers, 30 authors, 75 books,
--        150 students, 500 issue records (~450 already returned,
--        ~50 currently out — 35 within their loan period, 15 overdue),
--        realistic fine paid/partial/unpaid mix.
--
-- Schema, views, functions, procedures and triggers are untouched —
-- this file only INSERTs/UPDATEs data using the existing objects
-- (e.g. fine_amount is computed via the real fn_calculate_fine()).
-- =====================================================================
USE library_management_system;
""")

# =====================================================================
# SETTINGS + ADMINS — unchanged from the original seed (not "dataset")
# =====================================================================
emit("""-- ---------------------------------------------------------------------
-- Settings (unchanged — system configuration, not demo dataset)
-- ---------------------------------------------------------------------
INSERT INTO settings (setting_key, setting_value, description) VALUES
('fine_per_day',          '5.00', 'Late fine charged per day, in INR'),
('max_fine_per_book',   '500.00', 'Ceiling on fine for a single issue'),
('max_books_per_student',    '3', 'Maximum books a student may hold at once'),
('default_issue_days',      '14', 'Default loan period in days');

-- ---------------------------------------------------------------------
-- Admins (unchanged — documented demo login: admin / Admin@123)
-- ---------------------------------------------------------------------
INSERT INTO admins (username, password_hash, full_name, email, role) VALUES
('admin',     '$2b$12$/uhh/4xtx6caKzMRhOCvreAyVU3c3RiLn9atJLvGaw5OcJslds8Te', 'System Administrator', 'admin@citylibrary.local', 'super_admin'),
('librarian1','$2b$12$/uhh/4xtx6caKzMRhOCvreAyVU3c3RiLn9atJLvGaw5OcJslds8Te', 'Priya Sharma',          'priya.sharma@citylibrary.local', 'librarian');
""")

# =====================================================================
# CATEGORIES (10)
# =====================================================================
categories = [
    ("Computer Science", "Programming, algorithms, systems and data"),
    ("Mathematics", "Pure and applied mathematics"),
    ("Physics", "Classical and modern physics"),
    ("Literature", "Fiction and literary classics"),
    ("Biography", "Life stories of notable people"),
    ("History", "World and regional history"),
    ("Business & Economics", "Management, finance and economics"),
    ("Self-Help", "Personal development and productivity"),
    ("Electronics", "Circuits, embedded systems and hardware"),
    ("Philosophy", "Philosophical works and thought"),
]
emit("-- ---------------------------------------------------------------------\n-- Categories (10)\n-- ---------------------------------------------------------------------")
emit("INSERT INTO categories (category_name, description) VALUES")
emit(",\n".join(f"('{esc(n)}', '{esc(d)}')" for n, d in categories) + ";\n")

# =====================================================================
# PUBLISHERS (15)
# =====================================================================
publishers = [
    ("Pearson Education", "Noida, India", "contact@pearson.example", "0120-4567890"),
    ("O'Reilly Media", "Sebastopol, CA, USA", "orders@oreilly.example", "+1-707-8271000"),
    ("Penguin Random House", "New Delhi, India", "info@penguin.example", "011-42345678"),
    ("McGraw Hill", "New York, USA", "support@mheducation.example", "+1-212-9048000"),
    ("Wiley India", "New Delhi, India", "wileyindia@wiley.example", "011-43635444"),
    ("Oxford University Press", "Oxford, UK", "enquiry@oup.example", "+44-1865-556767"),
    ("Cambridge University Press", "Cambridge, UK", "info@cambridge.example", "+44-1223-358331"),
    ("HarperCollins", "Noida, India", "contact@harpercollins.example", "0120-4044800"),
    ("Springer", "Berlin, Germany", "service@springer.example", "+49-30-8270"),
    ("Manning Publications", "Shelter Island, USA", "orders@manning.example", "+1-877-6266263"),
    ("Addison-Wesley Professional", "Boston, USA", "aw.orders@pearson.example", "+1-617-8483000"),
    ("No Starch Press", "San Francisco, USA", "info@nostarch.example", "+1-415-2237800"),
    ("Bloomsbury Publishing", "London, UK", "contact@bloomsbury.example", "+44-20-74586300"),
    ("Macmillan Publishers", "London, UK", "info@macmillan.example", "+44-20-78336900"),
    ("Cengage Learning", "Boston, USA", "support@cengage.example", "+1-800-3549706"),
]
emit("-- ---------------------------------------------------------------------\n-- Publishers (15)\n-- ---------------------------------------------------------------------")
emit("INSERT INTO publishers (publisher_name, address, contact_email, phone) VALUES")
emit(",\n".join(f"('{esc(n)}', '{esc(a)}', '{esc(e)}', '{esc(p)}')" for n, a, e, p in publishers) + ";\n")
PUB = {n: i + 1 for i, (n, *_r) in enumerate(publishers)}
CAT = {n: i + 1 for i, (n, *_r) in enumerate(categories)}

# =====================================================================
# AUTHORS (30)
# =====================================================================
authors = [
    ("Thomas H. Cormen", "American"),
    ("Charles E. Leiserson", "American"),
    ("Robert C. Martin", "American"),
    ("Bjarne Stroustrup", "Danish"),
    ("Herbert Schildt", "American"),
    ("Yashavant Kanetkar", "Indian"),
    ("Eric Matthes", "American"),
    ("Gilbert Strang", "American"),
    ("B.S. Grewal", "Indian"),
    ("Sheldon Ross", "American"),
    ("Stephen Hawking", "British"),
    ("Arthur Beiser", "American"),
    ("H.C. Verma", "Indian"),
    ("Agatha Christie", "British"),
    ("George Orwell", "British"),
    ("R.K. Narayan", "Indian"),
    ("Chetan Bhagat", "Indian"),
    ("Walter Isaacson", "American"),
    ("APJ Abdul Kalam", "Indian"),
    ("Yuval Noah Harari", "Israeli"),
    ("Ramchandra Guha", "Indian"),
    ("Napoleon Hill", "American"),
    ("Robert Kiyosaki", "American"),
    ("Malcolm Gladwell", "Canadian"),
    ("James Clear", "American"),
    ("Paulo Coelho", "Brazilian"),
    ("Dale Carnegie", "American"),
    ("Thomas L. Floyd", "American"),
    ("Morris Mano", "American"),
    ("Plato", "Ancient Greek"),
]
emit("-- ---------------------------------------------------------------------\n-- Authors (30)\n-- ---------------------------------------------------------------------")
emit("INSERT INTO authors (author_name, nationality) VALUES")
emit(",\n".join(f"('{esc(n)}', '{esc(nat)}')" for n, nat in authors) + ";\n")
AUTH = {n: i + 1 for i, (n, *_r) in enumerate(authors)}

print("generated header/categories/publishers/authors", flush=False)

# =====================================================================
# BOOKS (75) — (title, category, [authors], publisher, edition, year, price, shelf_prefix, copies)
# =====================================================================
CS, MA, PH, LI, BI, HI, BE, SH, EL, PL = (
    "Computer Science", "Mathematics", "Physics", "Literature", "Biography",
    "History", "Business & Economics", "Self-Help", "Electronics", "Philosophy",
)
books = [
    # --- Computer Science (12) ---
    ("Introduction to Algorithms", CS, ["Thomas H. Cormen", "Charles E. Leiserson"], "McGraw Hill", "3rd", 2009, 899.00, "CS", 7),
    ("Clean Code", CS, ["Robert C. Martin"], "Pearson Education", "1st", 2008, 650.00, "CS", 8),
    ("Clean Architecture", CS, ["Robert C. Martin"], "Pearson Education", "1st", 2017, 699.00, "CS", 6),
    ("The C++ Programming Language", CS, ["Bjarne Stroustrup"], "Addison-Wesley Professional", "4th", 2013, 850.00, "CS", 5),
    ("Java: The Complete Reference", CS, ["Herbert Schildt"], "McGraw Hill", "11th", 2018, 695.00, "CS", 9),
    ("C++: The Complete Reference", CS, ["Herbert Schildt"], "McGraw Hill", "4th", 2002, 599.00, "CS", 6),
    ("C: The Complete Reference", CS, ["Herbert Schildt"], "McGraw Hill", "4th", 2000, 549.00, "CS", 7),
    ("Let Us C", CS, ["Yashavant Kanetkar"], "Wiley India", "17th", 2021, 375.00, "CS", 10),
    ("Let Us C++", CS, ["Yashavant Kanetkar"], "Wiley India", "5th", 2020, 399.00, "CS", 7),
    ("Data Structures Through C", CS, ["Yashavant Kanetkar"], "Wiley India", "1st", 2019, 425.00, "CS", 6),
    ("Pointers in C", CS, ["Yashavant Kanetkar"], "Wiley India", "3rd", 2015, 350.00, "CS", 5),
    ("Python Crash Course", CS, ["Eric Matthes"], "No Starch Press", "2nd", 2019, 599.00, "CS", 9),

    # --- Mathematics (7) ---
    ("Linear Algebra and Its Applications", MA, ["Gilbert Strang"], "Cengage Learning", "5th", 2016, 610.00, "MA", 5),
    ("Introduction to Linear Algebra", MA, ["Gilbert Strang"], "Cengage Learning", "5th", 2016, 590.00, "MA", 4),
    ("Calculus", MA, ["Gilbert Strang"], "Cengage Learning", "3rd", 2017, 550.00, "MA", 5),
    ("Differential Equations and Linear Algebra", MA, ["Gilbert Strang"], "Cengage Learning", "1st", 2014, 575.00, "MA", 4),
    ("Higher Engineering Mathematics", MA, ["B.S. Grewal"], "Wiley India", "44th", 2020, 550.00, "MA", 8),
    ("Numerical Methods in Engineering and Science", MA, ["B.S. Grewal"], "Wiley India", "10th", 2018, 480.00, "MA", 4),
    ("A First Course in Probability", MA, ["Sheldon Ross"], "Pearson Education", "9th", 2013, 690.00, "MA", 4),

    # --- Physics (7) ---
    ("A Brief History of Time", PH, ["Stephen Hawking"], "Penguin Random House", "1st", 1988, 399.00, "PH", 6),
    ("The Universe in a Nutshell", PH, ["Stephen Hawking"], "Penguin Random House", "1st", 2001, 425.00, "PH", 4),
    ("Concepts of Modern Physics", PH, ["Arthur Beiser"], "McGraw Hill", "6th", 2009, 615.00, "PH", 5),
    ("Concepts of Physics Part 1", PH, ["H.C. Verma"], "Oxford University Press", "1st", 2017, 350.00, "PH", 7),
    ("Concepts of Physics Part 2", PH, ["H.C. Verma"], "Oxford University Press", "1st", 2017, 350.00, "PH", 6),
    ("Quantum Physics for Beginners", PH, ["H.C. Verma"], "Oxford University Press", "1st", 2015, 399.00, "PH", 3),
    ("Quantum Mechanics: Concepts and Applications", PH, ["H.C. Verma"], "Oxford University Press", "2nd", 2019, 450.00, "PH", 3),

    # --- Literature (10) ---
    ("Murder on the Orient Express", LI, ["Agatha Christie"], "HarperCollins", "1st", 1934, 299.00, "LI", 8),
    ("And Then There Were None", LI, ["Agatha Christie"], "HarperCollins", "1st", 1939, 299.00, "LI", 9),
    ("The Murder of Roger Ackroyd", LI, ["Agatha Christie"], "HarperCollins", "1st", 1926, 275.00, "LI", 6),
    ("Death on the Nile", LI, ["Agatha Christie"], "HarperCollins", "1st", 1937, 299.00, "LI", 6),
    ("1984", LI, ["George Orwell"], "Penguin Random House", "1st", 1949, 299.00, "LI", 10),
    ("Animal Farm", LI, ["George Orwell"], "Penguin Random House", "1st", 1945, 225.00, "LI", 9),
    ("Malgudi Days", LI, ["R.K. Narayan"], "Penguin Random House", "1st", 1943, 250.00, "LI", 7),
    ("Swami and Friends", LI, ["R.K. Narayan"], "Penguin Random House", "1st", 1935, 250.00, "LI", 4),
    ("Five Point Someone", LI, ["Chetan Bhagat"], "Penguin Random House", "1st", 2004, 199.00, "LI", 9),
    ("2 States", LI, ["Chetan Bhagat"], "Penguin Random House", "1st", 2009, 199.00, "LI", 8),

    # --- Biography (5) ---
    ("Steve Jobs", BI, ["Walter Isaacson"], "Penguin Random House", "1st", 2011, 599.00, "BI", 6),
    ("Einstein: His Life and Universe", BI, ["Walter Isaacson"], "Macmillan Publishers", "1st", 2007, 550.00, "BI", 4),
    ("The Innovators", BI, ["Walter Isaacson"], "Macmillan Publishers", "1st", 2014, 525.00, "BI", 3),
    ("Wings of Fire", BI, ["APJ Abdul Kalam"], "HarperCollins", "1st", 1999, 275.00, "BI", 8),
    ("Ignited Minds", BI, ["APJ Abdul Kalam"], "Penguin Random House", "1st", 2002, 250.00, "BI", 5),

    # --- History (7) ---
    ("Sapiens: A Brief History of Humankind", HI, ["Yuval Noah Harari"], "Penguin Random House", "1st", 2015, 499.00, "HI", 8),
    ("Homo Deus", HI, ["Yuval Noah Harari"], "Penguin Random House", "1st", 2016, 499.00, "HI", 5),
    ("21 Lessons for the 21st Century", HI, ["Yuval Noah Harari"], "Penguin Random House", "1st", 2018, 499.00, "HI", 4),
    ("India After Gandhi", HI, ["Ramchandra Guha"], "HarperCollins", "2nd", 2017, 699.00, "HI", 5),
    ("Gandhi Before India", HI, ["Ramchandra Guha"], "Penguin Random House", "1st", 2013, 599.00, "HI", 3),
    ("Makers of Modern India", HI, ["Ramchandra Guha"], "Cambridge University Press", "1st", 2010, 650.00, "HI", 3),
    ("Patriots and Partisans", HI, ["Ramchandra Guha"], "Penguin Random House", "1st", 2012, 499.00, "HI", 3),

    # --- Business & Economics (8) ---
    ("Think and Grow Rich", BE, ["Napoleon Hill"], "Wiley India", "1st", 1937, 199.00, "BE", 8),
    ("Rich Dad Poor Dad", BE, ["Robert Kiyosaki"], "Wiley India", "1st", 1997, 299.00, "BE", 9),
    ("Cashflow Quadrant", BE, ["Robert Kiyosaki"], "Wiley India", "1st", 1998, 325.00, "BE", 4),
    ("Rich Dad's Guide to Investing", BE, ["Robert Kiyosaki"], "Wiley India", "1st", 2000, 350.00, "BE", 3),
    ("Outliers", BE, ["Malcolm Gladwell"], "Macmillan Publishers", "1st", 2008, 399.00, "BE", 6),
    ("The Tipping Point", BE, ["Malcolm Gladwell"], "Macmillan Publishers", "1st", 2000, 375.00, "BE", 5),
    ("Blink", BE, ["Malcolm Gladwell"], "Macmillan Publishers", "1st", 2005, 375.00, "BE", 4),
    ("David and Goliath", BE, ["Malcolm Gladwell"], "Macmillan Publishers", "1st", 2013, 399.00, "BE", 3),

    # --- Self-Help (6) ---
    ("Atomic Habits", SH, ["James Clear"], "Penguin Random House", "1st", 2018, 449.00, "SH", 10),
    ("The Alchemist", SH, ["Paulo Coelho"], "HarperCollins", "25th", 2014, 299.00, "SH", 9),
    ("Veronika Decides to Die", SH, ["Paulo Coelho"], "HarperCollins", "1st", 1998, 299.00, "SH", 4),
    ("How to Win Friends and Influence People", SH, ["Dale Carnegie"], "Macmillan Publishers", "1st", 1936, 299.00, "SH", 7),
    ("How to Stop Worrying and Start Living", SH, ["Dale Carnegie"], "Macmillan Publishers", "1st", 1948, 299.00, "SH", 4),
    ("How to Enjoy Your Life and Your Job", SH, ["Dale Carnegie"], "Macmillan Publishers", "1st", 1970, 275.00, "SH", 3),

    # --- Electronics (7) ---
    ("Electronic Devices and Circuit Theory", EL, ["Thomas L. Floyd"], "Pearson Education", "11th", 2015, 625.00, "EL", 5),
    ("Digital Fundamentals", EL, ["Thomas L. Floyd"], "Pearson Education", "11th", 2014, 599.00, "EL", 5),
    ("Principles of Electric Circuits", EL, ["Thomas L. Floyd"], "Pearson Education", "9th", 2009, 575.00, "EL", 3),
    ("Electric Circuits Fundamentals", EL, ["Thomas L. Floyd"], "Pearson Education", "8th", 2010, 550.00, "EL", 3),
    ("Digital Logic and Computer Design", EL, ["Morris Mano"], "Pearson Education", "1st", 1979, 499.00, "EL", 6),
    ("Computer System Architecture", EL, ["Morris Mano"], "Pearson Education", "3rd", 1992, 525.00, "EL", 4),
    ("Digital Design", EL, ["Morris Mano"], "Pearson Education", "6th", 2017, 599.00, "EL", 4),

    # --- Philosophy (6) ---
    ("The Republic", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 1998, 350.00, "PL", 5),
    ("Symposium", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 1994, 299.00, "PL", 3),
    ("Apology", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 1993, 249.00, "PL", 3),
    ("Phaedo", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 1993, 275.00, "PL", 2),
    ("Crito", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 1997, 225.00, "PL", 2),
    ("Timaeus", PL, ["Plato"], "Oxford University Press", "Oxford World's Classics", 2008, 299.00, "PL", 2),
]
assert len(books) == 75, f"expected 75 books, got {len(books)}"

emit("-- ---------------------------------------------------------------------\n-- Books (75)\n-- ---------------------------------------------------------------------")
shelf_counters = {}
book_rows = []
for title, cat, auths, pub, edition, year, price, shelf_prefix, copies in books:
    shelf_counters[shelf_prefix] = shelf_counters.get(shelf_prefix, 0) + 1
    shelf = f"{shelf_prefix}-{shelf_counters[shelf_prefix]:02d}"
    book_rows.append((title, cat, auths, pub, edition, year, price, shelf, copies))

isbn_seen = set()
def make_isbn(i):
    """A well-formed, checksum-valid ISBN-13 under the real 978 (Bookland)
    prefix — deterministic and unique per book, not a real catalog lookup,
    but structurally a genuine, valid ISBN-13."""
    first12 = f"978{100000000 + i * 9973 % 899999999:09d}"
    total = sum((1 if idx % 2 == 0 else 3) * int(d) for idx, d in enumerate(first12))
    check_digit = (10 - (total % 10)) % 10
    return first12 + str(check_digit)

lines = []
for i, (title, cat, auths, pub, edition, year, price, shelf, copies) in enumerate(book_rows, start=1):
    isbn = make_isbn(i)
    lines.append(
        f"('{isbn}', '{esc(title)}', {CAT[cat]}, {PUB[pub]}, '{esc(edition)}', {year}, "
        f"{copies}, {copies}, '{shelf}', {price:.2f})"
    )
emit("INSERT INTO books (isbn, title, category_id, publisher_id, edition, publication_year, total_copies, available_copies, shelf_location, price) VALUES")
emit(",\n".join(lines) + ";\n")

emit("-- ---------------------------------------------------------------------\n-- Book <-> Author mapping\n-- ---------------------------------------------------------------------")
ba_lines = []
for i, (title, cat, auths, pub, edition, year, price, shelf, copies) in enumerate(book_rows, start=1):
    for a in auths:
        ba_lines.append(f"({i}, {AUTH[a]})")
emit("INSERT INTO book_authors (book_id, author_id) VALUES")
emit(",\n".join(ba_lines) + ";\n")

print(f"generated {len(book_rows)} books, {len(ba_lines)} book_authors links")

# =====================================================================
# STUDENTS (150)
# =====================================================================
first_names = [
    "Aarav", "Ishaan", "Ananya", "Vivaan", "Diya", "Kabir", "Myra", "Reyansh",
    "Sara", "Arjun", "Aditi", "Krishna", "Riya", "Aryan", "Sanya", "Yash",
    "Pihu", "Dev", "Naina", "Om", "Advik", "Saanvi", "Vihaan", "Anika",
    "Rohan", "Kiara", "Aarush", "Navya", "Shaurya", "Zara", "Atharv", "Mahika",
    "Kian", "Avni", "Rudra", "Pari", "Ayaan", "Ira", "Darsh", "Tara",
    "Veer", "Anvi", "Samar", "Nisha", "Ranveer", "Kavya", "Dhruv", "Aisha",
    "Karan", "Meera", "Nikhil", "Simran", "Rahul", "Pooja", "Vikram", "Neha",
    "Aditya", "Priya", "Manav", "Isha", "Siddharth", "Tanvi", "Harsh", "Radhika",
    "Kunal", "Shreya", "Varun", "Aditi", "Rajat", "Nandini", "Akash", "Bhavya",
    "Gaurav", "Divya", "Nitin", "Swati", "Rajesh", "Pallavi", "Sanjay", "Ritu",
] * 2  # allow repeats when combined with distinct last names still gives 150 uniques

last_names = [
    "Sharma", "Verma", "Gupta", "Singh", "Patel", "Mehta", "Joshi", "Kumar",
    "Nair", "Reddy", "Chatterjee", "Malhotra", "Kapoor", "Agarwal", "Bhatt",
    "Choudhary", "Rastogi", "Yadav", "Iyer", "Khan", "Bansal", "Saxena",
    "Mishra", "Pandey", "Trivedi", "Desai", "Rao", "Menon", "Bose", "Dutta",
    "Chauhan", "Thakur", "Ahluwalia", "Bhalla", "Kohli", "Chandra", "Sinha",
    "Varma", "Suri", "Ghosh",
]
departments = [
    ("Computer Science", "CS"), ("Information Technology", "IT"),
    ("Electronics", "EC"), ("Mechanical", "ME"), ("Civil", "CV"),
]
dept_weights = [0.30, 0.22, 0.20, 0.16, 0.12]

random.shuffle(first_names)
name_pairs = []
seen_names = set()
fi, li = 0, 0
while len(name_pairs) < 150:
    fn = first_names[fi % len(first_names)]
    ln = last_names[(li + fi // len(first_names)) % len(last_names)]
    fi += 1
    if fi % len(first_names) == 0:
        li += 1
    full = f"{fn} {ln}"
    if full in seen_names:
        continue
    seen_names.add(full)
    name_pairs.append((fn, ln))

STUDENT_STATUS = (["active"] * 130) + (["inactive"] * 12) + (["blocked"] * 8)
random.shuffle(STUDENT_STATUS)

TODAY = date(2026, 7, 25)
students = []
dept_year_seq = {}
for idx in range(150):
    fn, ln = name_pairs[idx]
    dept_name, dept_code = random.choices(departments, weights=dept_weights, k=1)[0]
    year = random.choices([2022, 2023, 2024, 2025], weights=[0.15, 0.20, 0.30, 0.35], k=1)[0]
    key = (dept_code, year)
    dept_year_seq[key] = dept_year_seq.get(key, 0) + 1
    roll = f"BBD-{dept_code}-{year}{dept_year_seq[key]:02d}"
    email = f"{fn.lower()}.{ln.lower()}{idx}@student.bbd.example"
    phone = f"98{10000000 + idx:08d}"[:10]
    semester = random.randint(1, 8)
    membership_days_ago = random.randint(30, 1100)
    membership_date = TODAY - timedelta(days=membership_days_ago)
    status = STUDENT_STATUS[idx]
    students.append({
        "roll": roll, "name": f"{fn} {ln}", "email": email, "phone": phone,
        "dept": dept_name, "semester": semester, "membership_date": membership_date,
        "status": status,
    })

emit("-- ---------------------------------------------------------------------\n-- Students (150)\n-- ---------------------------------------------------------------------")
s_lines = []
for s in students:
    s_lines.append(
        f"('{esc(s['roll'])}', '{esc(s['name'])}', '{esc(s['email'])}', '{s['phone']}', "
        f"'{esc(s['dept'])}', {s['semester']}, '{s['membership_date'].isoformat()}', '{s['status']}')"
    )
emit("INSERT INTO students (roll_number, full_name, email, phone, department, semester, membership_date, status) VALUES")
emit(",\n".join(s_lines) + ";\n")

print(f"generated {len(students)} students "
      f"({STUDENT_STATUS.count('active')} active, {STUDENT_STATUS.count('inactive')} inactive, {STUDENT_STATUS.count('blocked')} blocked)")

# =====================================================================
# BOOK ISSUES (500 total: ~450 returned, ~50 currently out)
# =====================================================================
TOTAL_ISSUES = 500
CURRENTLY_ACTIVE = 50           # not yet returned
CURRENTLY_OVERDUE = 15          # subset of the above, past due date
CURRENTLY_ISSUED_OK = CURRENTLY_ACTIVE - CURRENTLY_OVERDUE  # 35, within loan period
HISTORICAL_RETURNED = TOTAL_ISSUES - CURRENTLY_ACTIVE       # 450

# Active students only may hold currently-active loans (mirrors sp_issue_book's
# rule that only 'active' students can be issued a book); returned historical
# loans can belong to any student status (a since-blocked/inactive member may
# well have borrowed-and-returned books while still active).
active_student_idxs = [i for i, s in enumerate(students) if s["status"] == "active"]

# Category popularity weighting -> how many historical loans each book tends
# to attract (bestsellers / core textbooks get borrowed far more than a
# single-copy philosophy dialogue).
POPULARITY = {
    CS: 1.3, MA: 0.8, PH: 0.7, LI: 1.4, BI: 1.0,
    HI: 0.9, BE: 1.3, SH: 1.5, EL: 0.7, PL: 0.5,
}
book_weights = [POPULARITY[b[1]] * b[8] / 5.0 for b in book_rows]  # also scale a bit by copy count

# Student engagement weighting -> a minority of members borrow much more than
# the rest (realistic power-law-ish usage), independent of current status.
student_weights = [random.choice([1, 1, 1, 2, 2, 3, 5]) for _ in students]

ADMIN_IDS = [1, 2]

# Track concurrently-active (unreturned) loans per book/student so we never
# violate available_copies or the 3-books-per-active-student rule.
active_count_per_book = [0] * len(book_rows)
active_count_per_student = [0] * len(students)

emit("-- ---------------------------------------------------------------------\n"
     "-- Book Issues (500) + Fine Payments\n"
     "-- Historical returned loans are written as INSERT (status='issued')\n"
     "-- immediately followed by an UPDATE to status='returned', mirroring\n"
     "-- exactly what sp_issue_book + sp_return_book would produce -- so\n"
     "-- available_copies is maintained purely by the existing triggers,\n"
     "-- with zero drift and no reconciliation step required.\n"
     "-- ---------------------------------------------------------------------")

def pick_book():
    return random.choices(range(len(book_rows)), weights=book_weights, k=1)[0]


def pick_student(active_only=False):
    pool = active_student_idxs if active_only else range(len(students))
    weights = [student_weights[i] for i in pool]
    return random.choices(list(pool), weights=weights, k=1)[0]


issue_rows = []  # for summary stats only

# --- Historical, already-returned loans (450) ------------------------------
# Spread issue_date over the last ~20 months with a mild recency bias.
SPAN_DAYS = 610
for n in range(HISTORICAL_RETURNED):
    b_idx = pick_book()
    s_idx = pick_student(active_only=False)

    days_ago = int(random.triangular(20, SPAN_DAYS, 90))  # more mass toward "more recent"
    issue_date = TODAY - timedelta(days=days_ago)
    loan_days = random.choice([7, 14, 14, 14, 21])
    due_date = issue_date + timedelta(days=loan_days)

    # 65% on-time-or-early, 35% late (by 1-45 days)
    if random.random() < 0.65:
        return_offset = random.randint(-5, 0)
    else:
        return_offset = random.randint(1, 45)
    return_date = due_date + timedelta(days=return_offset)
    if return_date > TODAY:
        return_date = TODAY

    issued_by = random.choice(ADMIN_IDS)
    returned_to = random.choice(ADMIN_IDS)

    emit(
        f"INSERT INTO book_issues (book_id, student_id, issue_date, due_date, issued_by, status) "
        f"VALUES ({b_idx + 1}, {s_idx + 1}, '{issue_date.isoformat()}', '{due_date.isoformat()}', {issued_by}, 'issued');"
    )
    emit("SET @iid := LAST_INSERT_ID();")
    emit(
        f"UPDATE book_issues SET return_date = '{return_date.isoformat()}', status = 'returned', "
        f"returned_to = {returned_to}, fine_amount = fn_calculate_fine(due_date, '{return_date.isoformat()}') "
        f"WHERE issue_id = @iid;"
    )
    issue_rows.append({"late": return_offset > 0})

# --- Currently active loans (50) -------------------------------------------
for n in range(CURRENTLY_ISSUED_OK):
    # find a book/student with headroom
    for _ in range(50):
        b_idx = pick_book()
        if active_count_per_book[b_idx] < book_rows[b_idx][8]:
            break
    for _ in range(50):
        s_idx = pick_student(active_only=True)
        if active_count_per_student[s_idx] < 3:
            break
    active_count_per_book[b_idx] += 1
    active_count_per_student[s_idx] += 1

    days_in = random.randint(1, 10)
    issue_date = TODAY - timedelta(days=days_in)
    loan_days = random.choice([7, 14, 14, 21])
    due_date = issue_date + timedelta(days=loan_days)
    if due_date <= TODAY:
        due_date = TODAY + timedelta(days=random.randint(1, 7))
    issued_by = random.choice(ADMIN_IDS)

    emit(
        f"INSERT INTO book_issues (book_id, student_id, issue_date, due_date, issued_by, status) "
        f"VALUES ({b_idx + 1}, {s_idx + 1}, '{issue_date.isoformat()}', '{due_date.isoformat()}', {issued_by}, 'issued');"
    )

for n in range(CURRENTLY_OVERDUE):
    for _ in range(50):
        b_idx = pick_book()
        if active_count_per_book[b_idx] < book_rows[b_idx][8]:
            break
    for _ in range(50):
        s_idx = pick_student(active_only=True)
        if active_count_per_student[s_idx] < 3:
            break
    active_count_per_book[b_idx] += 1
    active_count_per_student[s_idx] += 1

    days_overdue = random.randint(1, 25)
    loan_days = random.choice([7, 14, 21])
    due_date = TODAY - timedelta(days=days_overdue)
    issue_date = due_date - timedelta(days=loan_days)
    issued_by = random.choice(ADMIN_IDS)

    emit(
        f"INSERT INTO book_issues (book_id, student_id, issue_date, due_date, issued_by, status) "
        f"VALUES ({b_idx + 1}, {s_idx + 1}, '{issue_date.isoformat()}', '{due_date.isoformat()}', {issued_by}, 'overdue');"
    )

emit("")
emit("-- ---------------------------------------------------------------------")
emit("-- Fine collection: deterministic split over every returned-late issue")
emit("-- (fine_amount > 0), by MOD(issue_id, 10):")
emit("--   0-5 (60%) -> fully paid      6-7 (20%) -> partially paid      8-9 (20%) -> unpaid")
emit("-- ---------------------------------------------------------------------")
emit("""
UPDATE book_issues
   SET fine_paid = 1
 WHERE fine_amount > 0
   AND MOD(issue_id, 10) IN (0,1,2,3,4,5);

INSERT INTO fine_payments (issue_id, amount_paid, collected_by)
SELECT issue_id, fine_amount, returned_to
FROM book_issues
WHERE fine_paid = 1 AND fine_amount > 0;

-- Partial payments: pay roughly 40% of the fine, leave fine_paid = 0
INSERT INTO fine_payments (issue_id, amount_paid, collected_by)
SELECT issue_id, ROUND(fine_amount * 0.4, 2), returned_to
FROM book_issues
WHERE fine_amount > 0
  AND fine_paid = 0
  AND MOD(issue_id, 10) IN (6,7);

-- (MOD(issue_id,10) IN (8,9) rows are left fine_paid = 0 with no payment
-- row at all -- fully unpaid fines.)
""")

late_count = sum(1 for r in issue_rows if r["late"])
print(f"generated {TOTAL_ISSUES} book_issues "
      f"({HISTORICAL_RETURNED} returned [{late_count} late / {HISTORICAL_RETURNED - late_count} on-time], "
      f"{CURRENTLY_ISSUED_OK} currently issued, {CURRENTLY_OVERDUE} currently overdue)")

# =====================================================================
# WRITE OUTPUT
# =====================================================================
import pathlib
out_path = pathlib.Path(__file__).parent / "06_seed_data.sql"
out_path.write_text("\n".join(OUT) + "\n")
print(f"wrote {out_path} ({out_path.stat().st_size / 1024:.1f} KB)")



